version: "3"

tasks:
  api:up:
    desc: Run the API server
    cmd: go run ./cmd/api

  # Database tasks
  db:up:
    desc: Start PostgreSQL database
    cmd: docker-compose up -d postgres

  db:down:
    desc: Stop PostgreSQL database
    cmd: docker-compose down postgres

  minio:up:
    desc: Start MinIO server
    cmd: docker-compose up -d minio

  minio:down:
    desc: Stop MinIO server
    cmd: docker-compose down minio

  minio:create-bucket:
    desc: Create MinIO bucket
    cmd: docker-compose exec minio mc mb minioadmin/sorahenkan

  migrate:up:
    desc: Run all database migrations
    cmd: go run ./cmd/migrate -direction=up

  migrate:down:
    desc: Rollback all database migrations
    cmd: go run ./cmd/migrate -direction=down

  clean:
    desc: Clean build artifacts
    cmd: rm -rf bin/
