app:
  name: webserver
  version: 0.1.0
  env: base

database:
  host: localhost
  port: 5432
  user: sorahenkan
  password: sorahenkan_dev_password
  database: sorahenkan
  schema: public
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime_minutes: 5

image-processor:
  bucket_name: images

object-storer:
  endpoint: localhost:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  use_ssl: false
  region: us-east-1

watermill:
  image-topic: images
  broker:
    kind: sns
    publisher:
    subscriber:
    aws:
      anonymous: true
      endpoint: http://localhost:4566
      access_key: ""
      secret_key: ""
      region: us-east-1

http:
  port: 42069
  prefix: "/"
  ip: 0.0.0.0
  timeout: 5
  cors:
    origins:
      - "https://*"
      - "http://*"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    headers:
      - "Accept"
      - "Authorization"
      - "Content-Type"
      - "X-CSRF-Token"

opentelemetry:
  enabled: false
  endpoint: localhost:4317
  insecure: true
  interval: 20
  metrics:
    interval: 60
    timeout: 30
  traces:
    timeout: 30
    samplerate: 1
    batchsize: 512
    maxqueuesize: 1024
  logs:
    timeout: 30
    batchsize: 512
    maxqueuesize: 2048
    interval: 30
