// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BlurTransformationName.
const (
	BlurTransformationNameBlur BlurTransformationName = "blur"
)

// Defines values for GrayscaleTransformationName.
const (
	GrayscaleTransformationNameGrayscale GrayscaleTransformationName = "grayscale"
)

// Defines values for HealthStatus.
const (
	HealthStatusOK                       HealthStatus = "OK"
	HealthStatusPartiallyAvailable       HealthStatus = "Partially Available"
	HealthStatusTimeoutDuringHealthCheck HealthStatus = "Timeout during health check"
	HealthStatusUnavailable              HealthStatus = "Unavailable"
)

// Defines values for ResizeTransformationName.
const (
	ResizeTransformationNameResize ResizeTransformationName = "resize"
)

// Defines values for RotateConfigAngle.
const (
	RotateConfigAngleN180 RotateConfigAngle = 180
	RotateConfigAngleN270 RotateConfigAngle = 270
	RotateConfigAngleN90  RotateConfigAngle = 90
)

// Defines values for RotateTransformationName.
const (
	RotateTransformationNameRotate RotateTransformationName = "rotate"
)

// Defines values for TrimTransformationName.
const (
	TrimTransformationNameTrim TrimTransformationName = "trim"
)

// BlurConfig defines model for BlurConfig.
type BlurConfig struct {
	// Sigma Blur sigma value
	Sigma float64 `json:"sigma" validate:"required,gt=0"`
}

// BlurTransformation defines model for BlurTransformation.
type BlurTransformation struct {
	Config BlurConfig             `json:"config"`
	Name   BlurTransformationName `json:"name"`
}

// BlurTransformationName defines model for BlurTransformation.Name.
type BlurTransformationName string

// Component defines model for Component.
type Component struct {
	// Name Name is the name of the component.
	Name *string `json:"name,omitempty"`

	// Version Version is the component version.
	Version *string `json:"version,omitempty"`
}

// CreateImageRequest defines model for CreateImageRequest.
type CreateImageRequest struct {
	ImageUrl        string                  `json:"image_url" validate:"required,url"`
	Transformations []TransformationRequest `json:"transformations" validate:"required,min=1,dive"`
}

// CreateImageResponse defines model for CreateImageResponse.
type CreateImageResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// GrayscaleConfig No configuration needed for basic grayscale
type GrayscaleConfig = map[string]interface{}

// GrayscaleTransformation defines model for GrayscaleTransformation.
type GrayscaleTransformation struct {
	// Config No configuration needed for basic grayscale
	Config GrayscaleConfig             `json:"config"`
	Name   GrayscaleTransformationName `json:"name"`
}

// GrayscaleTransformationName defines model for GrayscaleTransformation.Name.
type GrayscaleTransformationName string

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Component *Component         `json:"component,omitempty"`
	Failures  *map[string]string `json:"failures,omitempty"`
	Status    *HealthStatus      `json:"status,omitempty"`
	System    *System            `json:"system,omitempty"`
	Timestamp *time.Time         `json:"timestamp,omitempty"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// Image defines model for Image.
type Image struct {
	Checksum              *string                  `json:"checksum,omitempty"`
	CreatedAt             *time.Time               `json:"created_at,omitempty"`
	ErrorMessage          *string                  `json:"error_message,omitempty"`
	Id                    *openapi_types.UUID      `json:"id,omitempty"`
	MimeType              *string                  `json:"mime_type,omitempty"`
	ObjectStorageImageKey *string                  `json:"object_storage_image_key,omitempty"`
	OriginalImageUrl      *string                  `json:"original_image_url,omitempty"`
	Status                *string                  `json:"status,omitempty"`
	Transformations       *[]TransformationRequest `json:"transformations,omitempty"`
	TransformedImageKey   *string                  `json:"transformed_image_key,omitempty"`
	UpdatedAt             *time.Time               `json:"updated_at,omitempty"`
}

// ListImagesResponse defines model for ListImagesResponse.
type ListImagesResponse struct {
	Count int     `json:"count"`
	Data  []Image `json:"data"`
	Limit int     `json:"limit"`
	Page  int     `json:"page"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message *string `json:"message,omitempty"`
}

// ResizeConfig defines model for ResizeConfig.
type ResizeConfig struct {
	Height int `json:"height" validate:"required,gte=1"`
	Width  int `json:"width" validate:"required,gte=1"`
}

// ResizeTransformation defines model for ResizeTransformation.
type ResizeTransformation struct {
	Config ResizeConfig             `json:"config"`
	Name   ResizeTransformationName `json:"name"`
}

// ResizeTransformationName defines model for ResizeTransformation.Name.
type ResizeTransformationName string

// RotateConfig defines model for RotateConfig.
type RotateConfig struct {
	// Angle Rotation angle in degrees
	Angle RotateConfigAngle `json:"angle" validate:"required,oneof=90 180 270"`
}

// RotateConfigAngle Rotation angle in degrees
type RotateConfigAngle int

// RotateTransformation defines model for RotateTransformation.
type RotateTransformation struct {
	Config RotateConfig             `json:"config"`
	Name   RotateTransformationName `json:"name"`
}

// RotateTransformationName defines model for RotateTransformation.Name.
type RotateTransformationName string

// System defines model for System.
type System struct {
	// AllocBytes AllocBytes is the bytes allocated and not yet freed.
	AllocBytes *int `json:"alloc_bytes,omitempty"`

	// GoroutinesCount GoroutinesCount is the number of the current goroutines.
	GoroutinesCount *int `json:"goroutines_count,omitempty"`

	// HeapObjectsCount HeapObjectsCount is the number of objects in the go heap.
	HeapObjectsCount *int `json:"heap_objects_count,omitempty"`

	// TotalAllocBytes TotalAllocBytes is the total bytes allocated.
	TotalAllocBytes *int `json:"total_alloc_bytes,omitempty"`

	// Version Version is the go version.
	Version *string `json:"version,omitempty"`
}

// TransformationRequest defines model for TransformationRequest.
type TransformationRequest struct {
	union json.RawMessage
}

// TrimConfig defines model for TrimConfig.
type TrimConfig struct {
	// Threshold Threshold for edge detection (0-255)
	Threshold float64 `json:"threshold" validate:"required,gte=0,lte=255"`
}

// TrimTransformation defines model for TrimTransformation.
type TrimTransformation struct {
	Config TrimConfig             `json:"config"`
	Name   TrimTransformationName `json:"name"`
}

// TrimTransformationName defines model for TrimTransformation.Name.
type TrimTransformationName string

// UpdateImageRequest defines model for UpdateImageRequest.
type UpdateImageRequest struct {
	Id              openapi_types.UUID      `json:"id" validate:"required,uuid"`
	Transformations []TransformationRequest `json:"transformations" validate:"required,min=1,dive"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Errors  map[string]interface{} `json:"errors"`
	Message string                 `json:"message"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateImageJSONRequestBody defines body for CreateImage for application/json ContentType.
type CreateImageJSONRequestBody = CreateImageRequest

// UpdateImageJSONRequestBody defines body for UpdateImage for application/json ContentType.
type UpdateImageJSONRequestBody = UpdateImageRequest

// AsResizeTransformation returns the union data inside the TransformationRequest as a ResizeTransformation
func (t TransformationRequest) AsResizeTransformation() (ResizeTransformation, error) {
	var body ResizeTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResizeTransformation overwrites any union data inside the TransformationRequest as the provided ResizeTransformation
func (t *TransformationRequest) FromResizeTransformation(v ResizeTransformation) error {
	v.Name = "resize"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResizeTransformation performs a merge with any union data inside the TransformationRequest, using the provided ResizeTransformation
func (t *TransformationRequest) MergeResizeTransformation(v ResizeTransformation) error {
	v.Name = "resize"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGrayscaleTransformation returns the union data inside the TransformationRequest as a GrayscaleTransformation
func (t TransformationRequest) AsGrayscaleTransformation() (GrayscaleTransformation, error) {
	var body GrayscaleTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGrayscaleTransformation overwrites any union data inside the TransformationRequest as the provided GrayscaleTransformation
func (t *TransformationRequest) FromGrayscaleTransformation(v GrayscaleTransformation) error {
	v.Name = "grayscale"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGrayscaleTransformation performs a merge with any union data inside the TransformationRequest, using the provided GrayscaleTransformation
func (t *TransformationRequest) MergeGrayscaleTransformation(v GrayscaleTransformation) error {
	v.Name = "grayscale"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrimTransformation returns the union data inside the TransformationRequest as a TrimTransformation
func (t TransformationRequest) AsTrimTransformation() (TrimTransformation, error) {
	var body TrimTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrimTransformation overwrites any union data inside the TransformationRequest as the provided TrimTransformation
func (t *TransformationRequest) FromTrimTransformation(v TrimTransformation) error {
	v.Name = "trim"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrimTransformation performs a merge with any union data inside the TransformationRequest, using the provided TrimTransformation
func (t *TransformationRequest) MergeTrimTransformation(v TrimTransformation) error {
	v.Name = "trim"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlurTransformation returns the union data inside the TransformationRequest as a BlurTransformation
func (t TransformationRequest) AsBlurTransformation() (BlurTransformation, error) {
	var body BlurTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlurTransformation overwrites any union data inside the TransformationRequest as the provided BlurTransformation
func (t *TransformationRequest) FromBlurTransformation(v BlurTransformation) error {
	v.Name = "blur"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlurTransformation performs a merge with any union data inside the TransformationRequest, using the provided BlurTransformation
func (t *TransformationRequest) MergeBlurTransformation(v BlurTransformation) error {
	v.Name = "blur"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRotateTransformation returns the union data inside the TransformationRequest as a RotateTransformation
func (t TransformationRequest) AsRotateTransformation() (RotateTransformation, error) {
	var body RotateTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRotateTransformation overwrites any union data inside the TransformationRequest as the provided RotateTransformation
func (t *TransformationRequest) FromRotateTransformation(v RotateTransformation) error {
	v.Name = "rotate"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRotateTransformation performs a merge with any union data inside the TransformationRequest, using the provided RotateTransformation
func (t *TransformationRequest) MergeRotateTransformation(v RotateTransformation) error {
	v.Name = "rotate"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TransformationRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"name"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TransformationRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "blur":
		return t.AsBlurTransformation()
	case "grayscale":
		return t.AsGrayscaleTransformation()
	case "resize":
		return t.AsResizeTransformation()
	case "rotate":
		return t.AsRotateTransformation()
	case "trim":
		return t.AsTrimTransformation()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TransformationRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TransformationRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+waa48at/avWL73QysNMJCs2iKtdJNNlKC2ySpk+2WFkHd8GNzM2BPbwy6N+O9XtmeY",
	"l3ltyaNqvgE+L5/3OeYTjkSaCQ5cKzz+hFW0hJTYj8+TXF4JvmCx+ZZJkYHUDBwYi1NiPlBQkWSZZoLj",
	"sUVB9gytSJIDDjA8REmu2Ap+Z5yleYrHWuYQ4IWQKdF4jKnI7xIDmZYAYYD1OgM8xjxP70DiAD/0BMlY",
	"LxIUYuA9eNCS9DSJrTArkjBKtEGQ8DFnEmgQ68sQbzabYPsTHt8WYs+29MXdnxBpvAms5O8l4crJZa/T",
	"vnS0VcZ/JSzwGP9nUClvUGhuUFPbJsCcpGAwgJub3eK7JJc1AZSWjMe4LafFCkqGPnmvSsZdMUuWTdO8",
	"ISkgppBeAjIQSCzs5+0N+rgjVYBXIFWhiya5P9xBSXFLBRUYHmob3zUkEA2TlMTwDj7moDz3YeZ0nsvE",
	"fNm6TS5Zh8Uj/MSQtZI1bO/4akjVIWs3faa8w8Z688QRGG7FJFKS9WOkTBm/HAaUraDr05V6ureYHVK5",
	"ygRX4NE5bSo7ZxQfclpGvfxeSinkbk5gjs2Hju+loBSJwXPm86RXkqxVRBKoUlYrAARy8ZRLqx3EAShQ",
	"tBAS3RHFIhSXJPA++ufJEm1xPamiEucM+eI1kEQvr5YQffCJXEsm+6Suss4mwAvCklw6CoRSZtRBkusG",
	"5Y5RO4IpTXR+MMyc+FMHa7DWSkN6CGvqoAxbloLSJM0abm3CrGeOjktWDSFqhnr7Kw7wNZGakSRZo2cr",
	"whLiatoNJ7Vv71kKIteI5oYJWlp6KLJGmXmyrw1Sj7kMgspTr4IjG950TvSxVw1cDM53x1twXD4wSS+F",
	"ufvVQ8Rpcq60kCZlucT1AdZ+YMlixkkyb6T/DljlPl1XO3dKb2TxOgOgBy6TZ/REo/j87zemtHUJtTud",
	"RiJ3YezpphjXEIM0pCjR5GiFODf0KCBhKXPMyINjNgzDWiM39LHOCh/bB9VKbxalZBcUdywu4Ut2vztP",
	"3q2l00rLO1DsL9jVCi+BxUt94EaP6mDhcmgFumdULz8fg5ayHbegvNdsp0LOUwgbyvVUQWnPz1EC3wlN",
	"9E4zEh4nnrbZIpluwZ4jxhGFWAIoM9o4EX8Jg+HPYTD6KZydwyyCg1hc/hKi4c8hGv3kmWKcqLuveCbD",
	"1NXlM4w9P4dhptti3jJJkohofrfW7mvTMM/M4XNzVs4gFhBZJJNsEeEUcaHRGjRaSABam0lq+SgWUuSa",
	"cVDzbfJssnq1hbgyANspyg6n2zkql9LMPxU5P7slkGzu7r6T4Wsg2VsHsoNjQcD4ozmIhWkmMj9HLTRJ",
	"5nuV+d6AdDVqMdt69TM5dlCMxYkTor8a24Bdv13g8e0x6aUVEZvgyOb8RLz3kqUnonj2DodQvEG+mQWY",
	"MqP4lHGi3UiVkiwzih1/cnuH42UIatPHiUoKypR9ikWCMp2ccmfTgbH0JGOUGWb9xmYzl5w21s1Yuqs0",
	"6KUEtRQJ9QROeWTHSKAxIAoaIlsyfgh7o4uLH7F32VV2TKOLi7OvvuAyDBINl6OLi271qG4z84ZbR2uP",
	"rB81jXqqh7XcGWrHje2sDyyQjhheHrM6MnT+4bsjeuTS6A9HmAl+zDpnz0rALX879Pc25HWJS8Cg5NSV",
	"1qAwvhCFq2oSWZ+AlLDEEM6zTEj9PyUkWQL/QHifCVx6KH52PUFTB2IHpUa4Wz9DmRQRKGVGeNNjNPWH",
	"FMgVi9y8EkGhpJJ4RqIloFE/xAG2Iy1eap2NB4P7+/s+sad9IeNBgaoGv02uXr6ZvuyN+mF/qdPEFnSQ",
	"qXq7mBaMtjTUPYljkH0mBhZkYIzLtE3hUyEJem2vi55dT3CtYuOwP+yHdubOgJOM4TF+0g/7T7AZ1vTS",
	"WnPglhV/mc8xWIUao9orT6hpkkC7/YgrANY9LOYoDEtLFBsmkmUJiyzq4E/lMoyLiePWQG6LZe3cNE+h",
	"EdNrOHHtlHoRPvkKAuS1zY8BVHmaErnGY2yxbTNULICKDrJyHBfOt9id45nBH6yGA7tkUIOaDVqNKmhE",
	"UEZi0wIARQlT2lB3eDhomazaJ1hLS5KCBhO8t23C18bttxWJmZ8+5iDXVdgUI3qlRQoLkifaprD9o36b",
	"mU19KAOJCqI+fuUuwMcwDE5YSJjG6bP5q2dj4/Gat78aN316Rr7NJO1hOeG2VCBZFZ2no9HZ+O8qFx5J",
	"KlC0ICwB6kL2i+pCg+QksQEIErkXiWbMGkNWYVTGZ/HDzPSVQnkC0r21III43Dv0evEold+Oy9oLDXbV",
	"D5R+Luj6bDrxPLu1egNTpzedyBh+Hgl228aB0a8dH+jOaP97kOwPkq6374iV3BMqrpEvgqTTUmnNeNyt",
	"YLXu/zNFime+OCpSzmea9jL7mywgVYCET7+gENZZuNBoIXJOvwfogQAtYozw3dHZ7DSVm168zebU8ulN",
	"gWv0cmWERUpLIKldhZAkKeolco9f3eCdWuhnSeI6pJst2IFQ0vCgB2A49hzD47VYvGR5Gncnedkrb2X+",
	"0lZ0cpjmIOfFoAq0ZcVCVq+GD9jzE6MbZ8kEtOe144X9fesg6G6NmFZo8qJjPAdZZt69w4OL0skL9MPN",
	"zeTFj2VDb0bLqp+3m4hmUq0394f+iTL7NhLw181931y+abmTvxvwJpd3oCWDlWkmTKucwEGHfAX6X+GN",
	"O1PYdx/0+uAr0JXvWL85Ikf+ncKHVAYRW7CoVUr85c+qsCp9/wDX/cLl91/l0CeU/0Za3NcAGGTrsT6X",
	"uiperZ1Pb5fSA9xdy11LQXP3sNWCXmqdqfFgQDLWq23VFwmkTPWjROTUvk8Wsnleu7d/g0PAaSYY16ry",
	"6GIL6lkU2runhJMYUnMLD3Khh81s8/8AAAD//99Uh7HqLgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
