// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BlurTransformationName.
const (
	BlurTransformationNameBlur BlurTransformationName = "blur"
)

// Defines values for GrayscaleTransformationName.
const (
	GrayscaleTransformationNameGrayscale GrayscaleTransformationName = "grayscale"
)

// Defines values for HealthStatus.
const (
	HealthStatusOK                       HealthStatus = "OK"
	HealthStatusPartiallyAvailable       HealthStatus = "Partially Available"
	HealthStatusTimeoutDuringHealthCheck HealthStatus = "Timeout during health check"
	HealthStatusUnavailable              HealthStatus = "Unavailable"
)

// Defines values for ResizeTransformationName.
const (
	ResizeTransformationNameResize ResizeTransformationName = "resize"
)

// Defines values for RotateConfigAngle.
const (
	RotateConfigAngleN180 RotateConfigAngle = 180
	RotateConfigAngleN270 RotateConfigAngle = 270
	RotateConfigAngleN90  RotateConfigAngle = 90
)

// Defines values for RotateTransformationName.
const (
	RotateTransformationNameRotate RotateTransformationName = "rotate"
)

// Defines values for TrimTransformationName.
const (
	TrimTransformationNameTrim TrimTransformationName = "trim"
)

// BlurConfig defines model for BlurConfig.
type BlurConfig struct {
	// Sigma Blur sigma value
	Sigma float64 `json:"sigma" validate:"required,gt=0"`
}

// BlurTransformation defines model for BlurTransformation.
type BlurTransformation struct {
	Config BlurConfig             `json:"config"`
	Name   BlurTransformationName `json:"name"`
}

// BlurTransformationName defines model for BlurTransformation.Name.
type BlurTransformationName string

// Component defines model for Component.
type Component struct {
	// Name Name is the name of the component.
	Name *string `json:"name,omitempty"`

	// Version Version is the component version.
	Version *string `json:"version,omitempty"`
}

// CreateImageRequest defines model for CreateImageRequest.
type CreateImageRequest struct {
	ImageUrl        string                  `json:"image_url" validate:"required,url"`
	Transformations []TransformationRequest `json:"transformations" validate:"required,min=1,dive"`
}

// CreateImageResponse defines model for CreateImageResponse.
type CreateImageResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// GrayscaleConfig No configuration needed for basic grayscale
type GrayscaleConfig = map[string]interface{}

// GrayscaleTransformation defines model for GrayscaleTransformation.
type GrayscaleTransformation struct {
	// Config No configuration needed for basic grayscale
	Config GrayscaleConfig             `json:"config"`
	Name   GrayscaleTransformationName `json:"name"`
}

// GrayscaleTransformationName defines model for GrayscaleTransformation.Name.
type GrayscaleTransformationName string

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Component *Component         `json:"component,omitempty"`
	Failures  *map[string]string `json:"failures,omitempty"`
	Status    *HealthStatus      `json:"status,omitempty"`
	System    *System            `json:"system,omitempty"`
	Timestamp *time.Time         `json:"timestamp,omitempty"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// Image defines model for Image.
type Image struct {
	Checksum              *string                  `json:"checksum,omitempty"`
	CreatedAt             *time.Time               `json:"created_at,omitempty"`
	Id                    *openapi_types.UUID      `json:"id,omitempty"`
	MimeType              *string                  `json:"mime_type,omitempty"`
	ObjectStorageImageKey *string                  `json:"object_storage_image_key,omitempty"`
	OriginalImageUrl      *string                  `json:"original_image_url,omitempty"`
	Status                *string                  `json:"status,omitempty"`
	Transformations       *[]TransformationRequest `json:"transformations,omitempty"`
	TransformedImageKey   *string                  `json:"transformed_image_key,omitempty"`
	UpdatedAt             *time.Time               `json:"updated_at,omitempty"`
}

// ListImagesResponse defines model for ListImagesResponse.
type ListImagesResponse struct {
	Count int     `json:"count"`
	Data  []Image `json:"data"`
	Limit int     `json:"limit"`
	Page  int     `json:"page"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message *string `json:"message,omitempty"`
}

// ResizeConfig defines model for ResizeConfig.
type ResizeConfig struct {
	Height int `json:"height" validate:"required,gte=1"`
	Width  int `json:"width" validate:"required,gte=1"`
}

// ResizeTransformation defines model for ResizeTransformation.
type ResizeTransformation struct {
	Config ResizeConfig             `json:"config"`
	Name   ResizeTransformationName `json:"name"`
}

// ResizeTransformationName defines model for ResizeTransformation.Name.
type ResizeTransformationName string

// RotateConfig defines model for RotateConfig.
type RotateConfig struct {
	// Angle Rotation angle in degrees
	Angle RotateConfigAngle `json:"angle" validate:"required,oneof=90 180 270"`
}

// RotateConfigAngle Rotation angle in degrees
type RotateConfigAngle int

// RotateTransformation defines model for RotateTransformation.
type RotateTransformation struct {
	Config RotateConfig             `json:"config"`
	Name   RotateTransformationName `json:"name"`
}

// RotateTransformationName defines model for RotateTransformation.Name.
type RotateTransformationName string

// System defines model for System.
type System struct {
	// AllocBytes AllocBytes is the bytes allocated and not yet freed.
	AllocBytes *int `json:"alloc_bytes,omitempty"`

	// GoroutinesCount GoroutinesCount is the number of the current goroutines.
	GoroutinesCount *int `json:"goroutines_count,omitempty"`

	// HeapObjectsCount HeapObjectsCount is the number of objects in the go heap.
	HeapObjectsCount *int `json:"heap_objects_count,omitempty"`

	// TotalAllocBytes TotalAllocBytes is the total bytes allocated.
	TotalAllocBytes *int `json:"total_alloc_bytes,omitempty"`

	// Version Version is the go version.
	Version *string `json:"version,omitempty"`
}

// TransformationRequest defines model for TransformationRequest.
type TransformationRequest struct {
	union json.RawMessage
}

// TrimConfig defines model for TrimConfig.
type TrimConfig struct {
	// Threshold Threshold for edge detection (0-255)
	Threshold float64 `json:"threshold" validate:"required,gte=0,lte=255"`
}

// TrimTransformation defines model for TrimTransformation.
type TrimTransformation struct {
	Config TrimConfig             `json:"config"`
	Name   TrimTransformationName `json:"name"`
}

// TrimTransformationName defines model for TrimTransformation.Name.
type TrimTransformationName string

// UpdateImageRequest defines model for UpdateImageRequest.
type UpdateImageRequest struct {
	Id              openapi_types.UUID      `json:"id" validate:"required,uuid"`
	Transformations []TransformationRequest `json:"transformations" validate:"required,min=1,dive"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Errors  map[string]interface{} `json:"errors"`
	Message string                 `json:"message"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateImageJSONRequestBody defines body for CreateImage for application/json ContentType.
type CreateImageJSONRequestBody = CreateImageRequest

// UpdateImageJSONRequestBody defines body for UpdateImage for application/json ContentType.
type UpdateImageJSONRequestBody = UpdateImageRequest

// AsResizeTransformation returns the union data inside the TransformationRequest as a ResizeTransformation
func (t TransformationRequest) AsResizeTransformation() (ResizeTransformation, error) {
	var body ResizeTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResizeTransformation overwrites any union data inside the TransformationRequest as the provided ResizeTransformation
func (t *TransformationRequest) FromResizeTransformation(v ResizeTransformation) error {
	v.Name = "resize"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResizeTransformation performs a merge with any union data inside the TransformationRequest, using the provided ResizeTransformation
func (t *TransformationRequest) MergeResizeTransformation(v ResizeTransformation) error {
	v.Name = "resize"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGrayscaleTransformation returns the union data inside the TransformationRequest as a GrayscaleTransformation
func (t TransformationRequest) AsGrayscaleTransformation() (GrayscaleTransformation, error) {
	var body GrayscaleTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGrayscaleTransformation overwrites any union data inside the TransformationRequest as the provided GrayscaleTransformation
func (t *TransformationRequest) FromGrayscaleTransformation(v GrayscaleTransformation) error {
	v.Name = "grayscale"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGrayscaleTransformation performs a merge with any union data inside the TransformationRequest, using the provided GrayscaleTransformation
func (t *TransformationRequest) MergeGrayscaleTransformation(v GrayscaleTransformation) error {
	v.Name = "grayscale"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrimTransformation returns the union data inside the TransformationRequest as a TrimTransformation
func (t TransformationRequest) AsTrimTransformation() (TrimTransformation, error) {
	var body TrimTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrimTransformation overwrites any union data inside the TransformationRequest as the provided TrimTransformation
func (t *TransformationRequest) FromTrimTransformation(v TrimTransformation) error {
	v.Name = "trim"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrimTransformation performs a merge with any union data inside the TransformationRequest, using the provided TrimTransformation
func (t *TransformationRequest) MergeTrimTransformation(v TrimTransformation) error {
	v.Name = "trim"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlurTransformation returns the union data inside the TransformationRequest as a BlurTransformation
func (t TransformationRequest) AsBlurTransformation() (BlurTransformation, error) {
	var body BlurTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlurTransformation overwrites any union data inside the TransformationRequest as the provided BlurTransformation
func (t *TransformationRequest) FromBlurTransformation(v BlurTransformation) error {
	v.Name = "blur"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlurTransformation performs a merge with any union data inside the TransformationRequest, using the provided BlurTransformation
func (t *TransformationRequest) MergeBlurTransformation(v BlurTransformation) error {
	v.Name = "blur"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRotateTransformation returns the union data inside the TransformationRequest as a RotateTransformation
func (t TransformationRequest) AsRotateTransformation() (RotateTransformation, error) {
	var body RotateTransformation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRotateTransformation overwrites any union data inside the TransformationRequest as the provided RotateTransformation
func (t *TransformationRequest) FromRotateTransformation(v RotateTransformation) error {
	v.Name = "rotate"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRotateTransformation performs a merge with any union data inside the TransformationRequest, using the provided RotateTransformation
func (t *TransformationRequest) MergeRotateTransformation(v RotateTransformation) error {
	v.Name = "rotate"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TransformationRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"name"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TransformationRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "blur":
		return t.AsBlurTransformation()
	case "grayscale":
		return t.AsGrayscaleTransformation()
	case "resize":
		return t.AsResizeTransformation()
	case "rotate":
		return t.AsRotateTransformation()
	case "trim":
		return t.AsTrimTransformation()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TransformationRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TransformationRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+waa2/btvavELz3wwootuw2d6uBALdNitbY1gR1si+BETDSscyVIlWScuIV/u8XJCXr",
	"Rb9y3cewfpPF8+J5nyN/xpFIM8GBa4VHn7GK5pAS+/ia5fJc8BlNzK9MigykpuDAaJIS8xCDiiTNNBUc",
	"jywKsmdoQVgOOMDwGLFc0QX8TjlN8xSPtMwhwDMhU6LxCMciv2cGMi0BwgDrZQZ4hHme3oPEAX48ESSj",
	"J5GIIQF+Ao9akhNNEivMgjAaE20QJHzKqYQ4SPRZiFerVbB+hUe3hdjTNX1x/ydEGq8CK/m1JFw5uex1",
	"2peO1sr4t4QZHuF/9Svl9QvN9WtqWwWYkxQMBnBzs1t8z3JZE0BpSXmC23JarKBk6JP3vGTcFbNk2TTN",
	"e5ICogrpOSADgcTMPq9v0MMdqQK8AKkKXTTJ/eEOSoprKqjA8FBb+a4hgWgYpySBD/ApB+W5DzWnd7lk",
	"5sfabXJJOyye4CeGrJWsYXvHV0Oqdlm76TPlHVbWm8eOwGAtJpGSLJ8iZUr52SCI6QK6Pl2pp3uL6S6V",
	"q0xwBR6dx01l5zTGu5yWxl5+b6QUcjMnMMfmoeN7KShFEvCc+TzprSRLFREGVcpqBYBALp5yabWDOEAM",
	"MZoJie6JohFKShJ4G/3jZIm2uJ5UUYlzhHzxDgjT8/M5RB99IteSyTapq6yzCvCMUJZLR4HEMTXqIOyq",
	"Qblj1I5gShOd7wwzJ/7EwRqspdKQ7sKaOCjDlqagNEmzhlubMDsxR/slq4YQNUNd/ooDfEWkpoSxJXq1",
	"IJQRV9NuOKn9uqYpiFyjODdM0NzSQ5E1ytSTfW2QesxlEFSeehUc2fCO74je96rBftFuUloKd+6th7HT",
	"053SQpqE5NLSR1j6gSVNKCfsrpHcO2CVc3Qd6dgJu5Gj6wwg3nGZPIsPVLnPu36jSluDq83JMhK5C1JP",
	"r0S5hgSkIRUTTfZWiHMyjwIYTaljRh4ds0EY1tq0gY91VnjsNqhW8rIoJbuguGNxCV8q+93Vhc1aOqxw",
	"fABF/4JNje4caDLXO270pP4UzgZWoAca6/mXY9BStuMWlPeablTIccpcQ7meGift+TEK3Aehid5oRsIT",
	"5mmKLZLpBew5ohzFkEgAZQYXJ+LLMBj8EgbDn8PpMcwiOIjZ2csQDX4J0fBnz4ziRN18xSMZpq4un2Hs",
	"+TEMM1mX6pZJGBPR3f1Su59Nw7wyh6/NWTlhWEBkkUyyRYTHiAuNlqDRTALEtYmjlo8SIUWuKQd1t06e",
	"TVZv1xDnBmA9I9nRcz0l5VKa6aYi52c3B5LdubtvZPgOSHbpQDZwLAgYfzQHiTCtQubnqIUm7G6rMq8N",
	"SFejFrOtVz+TfcfARBw4//mrsQ3Y5eUMj273SS+tiFgFe7beB+JdS5oeiOLZKuxC8Qb5ahrgmBrFp5QT",
	"7QamlGSZUezos9sq7C9DUJstDlRSUKbsQywSlOnkkDubDoymBxmjzDDL9zabueS0sm5G002lQc8lqLlg",
	"sSdwyiM7JEKcAIpBQ2RLxk/hyfD09Bn2rrLKjml4enr0xRachQHTcDY8Pe1Wj+o2U2+4dbT2xPpR06in",
	"eljLHaF23NjOesd6aI/h5SmLIUPnb74ZivdcCf3hCFPB91nWbBn43Wq3Q39rQ16XuAQMSk5daQ0K5TNR",
	"uKomkfUJSAllhnCeZULq/yohyRz4R8J7VODSQ/GrqzGaOBA7KDXC3foZyqSIQCkzoJseo6k/pEAuaOTm",
	"lQgKJZXEMxLNAQ17IQ6wHWnxXOts1O8/PDz0iD3tCZn0C1TV/218/ub95M3JsBf25jpltqCDTNXlbFIw",
	"WtNQDyRJQPao6FuQvjEu1TaFT4Qk6J29Lnp1Nca1io3D3qAX2pk7A04yikf4eS/sPcdmWNNza82+W0X8",
	"ZZ4TsAo1RrVXHsemSQLtth+uAFj3sJjDMCwtUeyPSJYxGlnU/p/KZRgXE/stedyOytq5aZ5CI6bXcOLa",
	"KfU0fP4NBMhrex0DqPI0JXKJR9hi22aoWO8UHWTlOC6cb7E7x1OD318M+nbJoPo1G7QaVdCIoIwkpgWA",
	"GDGqtKHu8HDQMlm1T7CWliQFDSZ4b9uEr4zbrysSNa8+5SCXVdgUI3qlxRhmJGfaprDto36bmU19KAOJ",
	"CqI+fuUuwMcwDA5YSJjG6Yv5q2dj4/Gay1+Nm744It9mkvawHHNbKpCsis6L4fBo/DeVC48kFSiaEcog",
	"diH7VXWhQXLCbACCRO57QzNmjSGrMCrjs3gxNX2lUJ6AdF9SEEEcHhx6vXiUym/HZe37C3bVD5R+LeLl",
	"0XTi+ajW6g1MnV51ImPwZSTYbBsHFn/r+ED3Rvs/gmR7kHS9fUOs5J5QcY18ESSdlkprypNuBat1/18o",
	"UjzzxV6RcjzTtJfZ32UBqQIkfPEVhbDOwoVGM5Hz+EeA7gjQIsYI3xydzU5TuenF22xOLJ+TCXCN3iyM",
	"sEhpCSS1qxDCWFEvkfv41Q3eiYV+xZjrkG7WYDtCScOj7oPheOIY7q/F4kuWp3F3kpe98lrmr21FJ4dp",
	"DnJeDKoQt6xYyOrV8A57fqbxylmSgfZ87biw79cOgu6XiGqFxhcd4znIMvNuHR5clI4v0E83N+OLZ2VD",
	"b0bLqp+3m4hmUq0397v+ZzL9PhLwt819312+abmTvxvwJpcPoCWFhWkmTKvMYKdDvgX9j/DGjSnshw96",
	"ffAt6Mp3rN/skSP/n8KHVAYRndGoVUr85c+qsCp9fwPX/crl9x/l0AeU/0Za3NYAGGTrsT6XuoAFMJGl",
	"xpcdVHsxzURE2FwoPXoxDP/zEnf3dV0a6Kd319dXk2cNWspHbLqW2PMNfP3XNwQ8zgTlWlV+XuxGPetD",
	"q5GUcJKAlcmDXGhnNV39LwAA///ikd0Z3i4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
