basePath: /
definitions:
  github_com_taldoflemis_sora-henkan_internal_core_domain_images.CreateImageRequest:
    properties:
      image_url:
        type: string
      transformations:
        items:
          $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.TransformationRequest'
        minItems: 1
        type: array
    required:
    - image_url
    - transformations
    type: object
  github_com_taldoflemis_sora-henkan_internal_core_domain_images.CreateImageResponse:
    properties:
      id:
        type: string
    type: object
  github_com_taldoflemis_sora-henkan_internal_core_domain_images.Image:
    properties:
      checksum:
        type: string
      created_at:
        type: string
      id:
        type: string
      mime_type:
        type: string
      object_storage_image_key:
        type: string
      original_image_url:
        type: string
      status:
        type: string
      transformations:
        items:
          $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.TransformationRequest'
        type: array
      transformed_image_key:
        type: string
      updated_at:
        type: string
    type: object
  github_com_taldoflemis_sora-henkan_internal_core_domain_images.ListImagesResponse:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.Image'
        type: array
      limit:
        type: integer
      page:
        type: integer
    type: object
  github_com_taldoflemis_sora-henkan_internal_core_domain_images.TransformationRequest:
    properties:
      config:
        additionalProperties: true
        type: object
      name:
        type: string
    type: object
  github_com_taldoflemis_sora-henkan_internal_core_domain_images.UpdateImageRequest:
    properties:
      id:
        type: string
      transformations:
        items:
          $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.TransformationRequest'
        minItems: 1
        type: array
    required:
    - id
    - transformations
    type: object
  health.Check:
    properties:
      component:
        allOf:
        - $ref: '#/definitions/health.Component'
        description: Component holds information on the component for which checks
          are made
      failures:
        additionalProperties:
          type: string
        description: Failures holds the failed checks along with their messages.
        type: object
      status:
        allOf:
        - $ref: '#/definitions/health.Status'
        description: Status is the check status.
      system:
        allOf:
        - $ref: '#/definitions/health.System'
        description: System holds information of the go process.
      timestamp:
        description: Timestamp is the time in which the check occurred.
        type: string
    type: object
  health.Component:
    properties:
      name:
        description: Name is the name of the component.
        type: string
      version:
        description: Version is the component version.
        type: string
    type: object
  health.Status:
    enum:
    - OK
    - Partially Available
    - Unavailable
    - Timeout during health check
    type: string
    x-enum-varnames:
    - StatusOK
    - StatusPartiallyAvailable
    - StatusUnavailable
    - StatusTimeout
  health.System:
    properties:
      alloc_bytes:
        description: TotalAllocBytes is the bytes allocated and not yet freed.
        type: integer
      goroutines_count:
        description: GoroutinesCount is the number of the current goroutines.
        type: integer
      heap_objects_count:
        description: HeapObjectsCount is the number of objects in the go heap.
        type: integer
      total_alloc_bytes:
        description: TotalAllocBytes is the total bytes allocated.
        type: integer
      version:
        description: Version is the go version.
        type: string
    type: object
  internal_infra_handler_http.ValidationErrorResponse:
    properties:
      errors:
        additionalProperties: true
        type: object
      message:
        type: string
    type: object
host: localhost:42069
info:
  contact:
    email: support@sorahenkan.io
    name: API Support
  description: Image processing and transformation service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Sora Henkan API
  version: 0.1.0
paths:
  /healthz:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/health.Check'
        "503":
          description: Service is unavailable
          schema:
            $ref: '#/definitions/health.Check'
      summary: Check the health of the service
      tags:
      - health
  /v1/images/:
    get:
      consumes:
      - application/json
      description: Get a paginated list of images
      parameters:
      - default: 1
        description: Page number
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.ListImagesResponse'
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "422":
          description: Validation failed
          schema:
            $ref: '#/definitions/internal_infra_handler_http.ValidationErrorResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: List images
      tags:
      - images
    post:
      consumes:
      - application/json
      description: Create a new image processing request
      parameters:
      - description: Create image request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.CreateImageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.CreateImageResponse'
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "422":
          description: Validation failed
          schema:
            $ref: '#/definitions/internal_infra_handler_http.ValidationErrorResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new image
      tags:
      - images
    put:
      consumes:
      - application/json
      description: Update image transformation settings
      parameters:
      - description: Update image request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.UpdateImageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Image not found
          schema:
            additionalProperties: true
            type: object
        "422":
          description: Validation failed
          schema:
            $ref: '#/definitions/internal_infra_handler_http.ValidationErrorResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Update an image
      tags:
      - images
  /v1/images/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an image by its ID
      parameters:
      - description: Image ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Image not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Delete an image
      tags:
      - images
    get:
      consumes:
      - application/json
      description: Retrieve a single image by its ID
      parameters:
      - description: Image ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.Image'
        "404":
          description: Image not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get image by ID
      tags:
      - images
  /v1/images/{id}/sse:
    get:
      description: Server-Sent Events stream for a specific image updates
      parameters:
      - description: Image ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/event-stream
      responses:
        "200":
          description: Stream of image updates
          schema:
            $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.Image'
        "404":
          description: Image not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Streaming unsupported
          schema:
            additionalProperties: true
            type: object
      summary: Stream single image updates
      tags:
      - images
  /v1/images/sse:
    get:
      description: Server-Sent Events stream for all images updates
      produces:
      - text/event-stream
      responses:
        "200":
          description: Stream of image updates
          schema:
            $ref: '#/definitions/github_com_taldoflemis_sora-henkan_internal_core_domain_images.Image'
        "500":
          description: Streaming unsupported
          schema:
            additionalProperties: true
            type: object
      summary: Stream all images updates
      tags:
      - images
schemes:
- http
- https
swagger: "2.0"
