name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: ["main"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Build API
        run: go build -v ./cmd/api

      - name: Build Worker
        run: go build -v ./cmd/worker

      - name: Build Migrate
        run: go build -v ./cmd/migrate

      - name: Test
        run: go test -v ./...
